Exception in thread Thread-1 (_handle_workers):
Traceback (most recent call last):
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/multiprocessing/pool.py", line 516, in _handle_workers
    cls._maintain_pool(ctx, Process, processes, pool, inqueue,
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/multiprocessing/pool.py", line 340, in _maintain_pool
    Pool._repopulate_pool_static(ctx, Process, processes, pool,
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/amp587/.conda/envs/hpc/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
